apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: fields-service
  name: fields-service
spec:
  containers:
    - image: sachingorade/fields-service
      name: fields-service
      resources: {}
    - image: mongo
      name: mongodb
      ports:
        - containerPort: 27017
          hostPort: 27017
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}